### ISSUE TITLE
Feature: prime k-tuplets interface

### ISSUE THREAD

**Issue by JulStrat** [kimwalisch/primesieve#100]
Good day , Kim.

I think it would be nice feature if you implement something like this
primesieve_generate_twins(start, stop)
primesieve_generate_triplets(start, stop)
...
primesieve_generate_sextuplets(start, stop)

( or may be k-tuplet iterator ? )

where each function returns array of (first element of the k-tuplet and pattern **if needed**).
IMO primesieve_print_*()  are not very useful for prime tuplet processing / analyzing.

Best Regards
 Julian.

**Comment by kimwalisch** [comment]
Hi Julian,

I agree that the ```primesieve_print_*()``` functions are useless. However I won't remove them because that would break backwards compatibility. Since the beginning, my goal for primesieve and primecount was to write libraries that are extremely specialized i.e. primesieve should generate primes as quickly as possible and primecount should count primes as quickly as possible. So unlike many other libraries my goal was never to create a library for doing number theory with lots of number theoretic functions.

After more than a decade of hard work, I am both happy and relieved that I have finally achieved my goals. This means that for me personally, both primesieve and primecount are now feature complete. My new goals for the future are:  to maintain primesieve and primecount with hopefully as little effort as possible and to use my free time for my other hobbies.

I guess it is a good idea, for me to open a new issue  "No new feature requests" so that other users can read about the status of my libraries and what they can expect of my libraries.

Best regards,
Kim

**Comment by JulStrat** [comment]
It's clear. Thank you.
I will do it myself  :-) .

Regards and productive New Year!
Julian.
