### ISSUE TITLE
primesieve-python: what happened to it? `python3 -c $'import primesieve'` fails

### ISSUE THREAD

**Issue by shlomif** [kimwalisch/primesieve#132]
primesieve-python: what happened to it? `python3 -c $'import primesieve'` fails. see https://github.com/kimwalisch/primesieve-python/ . I volunteer to comaintain it.

**Comment by kimwalisch** [comment]
I stopped maintaining primesieve-python because it took too much time to do a new release every year when there was a new python release. We tried to make primesieve-python convenient for the user by distributing binary wheels, however I think this was a mistake, this dramatically increased the maintenance time. In theory building the binary wheels is handled fully automatically by external tools so doing a new primesieve-python release should be very easy and quick. However in practice, for every release there where multiple targets (OS + CPU) that failed and it always took me one or two weeks to fix all these issues.

> I volunteer to comaintain it.

I am willing to transfer ownership of primesieve-python to you if you are willing to maintain it. But I won't help maintaining it. After more than a decade of spending a significant portion of my free time on open source I now want to reduce my open source activities to a minimum. I still actively maintain primesieve and primecount but hopefully with as little effort as possible.

**Comment by shlomif** [comment]
thanks for the reply.

> > I volunteer to comaintain it.
> 
> I am willing to transfer ownership of primesieve-python to you if you are willing to maintain it. But I won't help maintaining it. After more than a decade of spending a significant portion of my free time on open source I now want to reduce my open source activities to a minimum. I still actively maintain primesieve and primecount but hopefully with as little effort as possible.

Please do. I am https://pypi.org/user/shlomif-gmail/ on pypi

**Comment by kimwalisch** [comment]
I have sent you an invite to join primesieve-python as owner on pypi.

I also tried to transfer ownership my primesieve-python repo to you, however I think this did not work because you already have a fork of it: https://github.com/shlomif/primesieve-python. If you also want the ownership of my primesieve-python repo then you need to delete yours first...

**Comment by shlomif** [comment]
> I have sent you an invite to join primesieve-python as owner on pypi.
> 

accepted.

> I also tried to transfer ownership of my primesieve-python repo to you, however I think this did not work because you already have a fork of it: https://github.com/shlomif/primesieve-python. If you also want the ownership of my primesieve-python repo then you need to delete your's first...

deleted.

thanks.

**Comment by shlomif** [comment]
@kimwalisch :

**Comment by shlomif** [comment]
@kimwalisch : thanks! the repo was transferred, and I uploaded v2.3.1 with a fix.

**Comment by kimwalisch** [comment]
Great!
