### ISSUE TITLE
how can you search prime numbers with in a certain range like

### ISSUE THREAD

**Issue by brainwant** [kimwalisch/primesieve#133]
searching prime numbers between 100000<range<1000000 how to make this ranged  search primes with in a certain range

**Comment by kimwalisch** [comment]
* Range based search using primesieve command-line program: ```primesieve 100000+1 1000000-1 --print```
* Range based search using C API: https://github.com/kimwalisch/primesieve/blob/master/doc/C_API.md#primesieve_jump_to-since-primesieve-110
* Range based search using C++ API: https://github.com/kimwalisch/primesieve/blob/master/doc/CPP_API.md#primesieveiteratorjump_to-since-primesieve-110

Please note that for simple use cases you can often write a bash script using the primesieve command-line program. However for more complex use cases the C/C++ API is better suited. If you don't know C or C++ you can use primesieve bindings for other programming languages such as e.g.: [https://github.com/shlomif/primesieve-python](primesieve-python).
