### ISSUE TITLE
macro for the largest valid stop number for primesieve

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#14]
Please introduce a macro for the largest valid stop number for primesieve, i.e., the value effectively returned by primesieve_get_max_stop(). This is a C oriented request, I guess, the rational is to allow to set up some macros accordingly at precompile time.
BTW, I noticed that this value is not (2^64-1)-(2^32-1)*10 as written in the API doc, but
(2^64-1)-(2^32-1)*10-1 .

**Comment by kimwalisch** [comment]
> I noticed that this value is not ```(2^64-1)-(2^32-1)*10``` as written in the API doc, but ```(2^64-1)-(2^32-1)*10-1```.

```
(2^64-1)-(2^32-1)*10 = 18446744030759878665
(2^64-1)-(2^32-1)*10-1 = 18446744030759878664
```

My tests show that both:

```
primesieve::get_max_stop()
primesieve_get_max_stop()
```

return ```18446744030759878665``` which corresponds to ```(2^64-1)-(2^32-1)*10``` as written in the API doc. So I think everything is correct.

**Comment by kimwalisch** [comment]
> Please introduce a macro for the largest valid stop number for primesieve, i.e., the value effectively returned by primesieve_get_max_stop(). This is a C oriented request, I guess, the rational is to allow to set up some macros accordingly at precompile time.

I don't like this idea because ```primesieve::get_max_stop()``` is currently calculated dynamically:

```c++
/// @file WheelFactorization.hpp

static uint64_t getMaxStop()
{
  const uint64_t MAX_UINT32 = std::numeric_limits<uint32_t>::max();
  const uint64_t MAX_UINT64 = std::numeric_limits<uint64_t>::max();

  return MAX_UINT64 - MAX_UINT32 * getMaxFactor();
}
```

Currently it is possible for me switch to a bigger or smaller wheel and the max stop number is then automatically adjusted. I regularly switch wheels for testing purpose (e.g. use 3rd Wheel instead of 4th Wheel in EratMedium and EratBig).

Currently switching wheels in primesieve works by deriving (inheriting) from a different wheel e.g.:

```c++
// Uses 4th wheel
class EratBig: public Modulo210Wheel_t { ... };

// Uses 3rd wheel
class EratBig: public Modulo30Wheel_t { ... }
```

There is no way for me to automatically adjust the value of a PRIMESIEVE_MAX_STOP macro when switching wheels. Not providing a PRIMESIEVE_MAX_STOP macro also allows me to e.g. improve primesieve by implementing an even larger 5th wheel without breaking backwards compatibility.

**Comment by jgmbenoit** [comment]
Concerning the return value, you are right: I have just realized that I enter (2^64)-(2^32)*10 instead of (2^64-)-(2^32-1)*10 .
Otherwise, of course if this value is dynamic, introducing a macro is a non-sense.
On the other hand, in the API document, it must be clear that this value is dynamic and not a constant.
Besides, what is upper bounder ? does it deserve a macro ?
