### ISSUE TITLE
Riemann_R test fails on aarch64 and s390x architecture

### ISSUE THREAD

**Issue by folliehiyuki** [kimwalisch/primesieve#147]
I'm updating `primesieve` package for AlpineLinux to 12.0 in https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61519.

The CI fails for `aarch64` and `s390x` architecture with Riemann_R test:
```python
...
Test project /builds/folliehiyuki/aports/testing/primesieve/src/primesieve-12.0/build
      Start  1: Riemann_R
      Start  2: calculator
      Start  3: clear_primesieve_iterator1
      Start  4: clear_primesieve_iterator2
      Start  5: count_primes1
      Start  6: count_primes2
      Start  7: count_primes3
      Start  8: count_quadruplets
 1/33 Test  #1: Riemann_R ........................***Failed    0.05 sec
RiemannR(10) = 4   OK
RiemannR(100) = 25   OK
RiemannR(1000) = 168   OK
RiemannR(10000) = 1226   OK
RiemannR(100000) = 9587   OK
RiemannR(1000000) = 78527   OK
RiemannR(10000000) = 664667   OK
RiemannR(100000000) = 5761551   OK
RiemannR(1000000000) = 50847455   OK
RiemannR(10000000000) = 455050683   OK
RiemannR(100000000000) = 4118052494   OK
RiemannR(1000000000000) = 37607910542   OK
RiemannR(10000000000000) = 346065531065   OK
RiemannR(100000000000000) = 3204941731601   OK
RiemannR(1000000000000000) = 29844570495886   OK
RiemannR(10000000000000000) = 279238341360978   ERROR
...
```

Can you provide some information on why it's failing?

The build logs can be seen here:
* aarch64: https://gitlab.alpinelinux.org/folliehiyuki/aports/-/jobs/1296844
* s390x: https://gitlab.alpinelinux.org/folliehiyuki/aports/-/jobs/1296845

**Comment by kimwalisch** [comment]
> Can you provide some information on why it's failing?

Yes, the RiemannR function uses floating point instructions and its accuracy may differ for different compilers and CPU architectures. The test needs to use the least common denominator .i.e. only test up to a number x which passes successfully on all compilers and CPU architectures.

Based on your feedback I will decrease the maximum number to be tested to 10^15. And I will release primesieve-12.1 within the next few days

**Comment by kimwalisch** [comment]
On arm64 Alpine Linux ```sizeof(long double)=16``` so in theory ```long double``` on arm64 should be much more accurate than on x86_64 where ```long double``` has 80 bits.

However unexpectedly the accuracy of floating point algorithms using the long double type on arm64 Alpine Linux does not increase compared to when using the double type. The issue is likely caused by musl libc because this test failure does not occur using arm64 with OpenSuse or Fedora (which use libm from glibc). Hence for my tests it is best to always assume double precision and not do any extended precision tests using long double.

> https://wiki.musl-libc.org/mathematical-library
> Supported long double formats: IEEE-754 binary64 (ld64) and x86 80 bit extended precision format (ld80) are fully supported and there is partial support for IEEE-754 binary128 (ld128).

Hence 128-bit long double is not fully supported by musl libc and it looks like logl(x) (using long double type) falls back to double type when using the musl libc on arm64.

**Comment by folliehiyuki** [comment]
Thanks for all the explanation! I saw you released 12.1 and tried it in the CI. The previously failed tests indeed passed now.

This time `iroot` test failed on riscv64. Can you also look into it?

Ref: https://gitlab.alpinelinux.org/folliehiyuki/aports/-/pipelines/217890

**Comment by kimwalisch** [comment]
> Ref: https://gitlab.alpinelinux.org/folliehiyuki/aports/-/pipelines/217890
> This time iroot test on primecount project failed on riscv64. Can you also look into it? I can create a separated issue on that project if you want to. This issue can be closed.

```
iroot<6>(4092) = 3   OK
iroot<6>(4093) = 3   OK
iroot<6>(4094) = 3   OK
iroot<6>(4095) = 3   OK
iroot<6>(4096) = 4   ERROR
```

I think I have already fixed this issue (only test ```iroot<6>(x)``` for x < 4096) on the primecount master branch yesterday: https://github.com/kimwalisch/primecount/commit/fac0b4e37d465397bf0414c6c6edb57e1158ed5c. I even installed arm64 Alpine Linux in a virtual machine and now all unit tests pass successfully on both primesieve (12.1) and primecount (master branch).

Maybe this error is caused because you are not using the very lastest primecount source code?

**Comment by kimwalisch** [comment]
I made another [commit](https://github.com/kimwalisch/primecount/commit/f83adef47a5360c00554c739c6ab2a1be7c97ae9) to the primecount project, now ```test/iroot.cpp``` does not rely on the math functions from the libc anymore.

In fact I have removed ```std::pow()``` and ```std::cbrt()``` from all primesieve and primecount unit tests. Based on your feedback, there is simply a big risk that those functions are inaccurate (off by 1 when converted to an integer) in one of the many libc out there (on some niche CPU architecture).

**Comment by folliehiyuki** [comment]
> Maybe this error is caused because you are not using the very lastest primecount source code?

You're right. In the old commit there I was just trying to rebuild primecount 7.10 against the newer version of primesieve.

I pushed the newer primecount version to the MR and CI on all architectures already passed. Thanks again for looking into the issue!
