### ISSUE TITLE
Installation of primesieve-python fails in primesieve

### ISSUE THREAD

**Issue by rogerl50** [kimwalisch/primesieve#155]
I'm trying to install the primesieve-python bindings for primesieve. When I do what I think the instructions say and run `pip install primesieve`, I eventually get 
```
    primesieve/_primesieve.cpp:1264:10: fatal error: 'primesieve.h' file not found"
     1264 | #include "primesieve.h".
```
I have g++ 14.2 installed via homebrew. Obviously I've missed some step. Can you help? Thanks. (I realize that you are the maintainer of the C++ library, not the bindings, but I'm been unable to get a response there.)

**Comment by kimwalisch** [comment]
Hi,

Unfortunately I cannot help you with this. I used to be a maintainer of this project and we distributed binary wheels which made its installation dead simple. But it became virtually impossible to maintain these binary wheels since Python's setup and distribution tools kept on making backwards incompatible changes all the time. So I gave up on maintaining this project.

I suggest you find another Python library that offers the same functionality for generating primes and that is easier to install such as SymPy: https://www.geeksforgeeks.org/prime-functions-python-sympy

If you really need the performance of libprimesieve, then I suggest to use its [C API](https://github.com/kimwalisch/primesieve/blob/master/doc/C_API.md) or its [C++ API](https://github.com/kimwalisch/primesieve/blob/master/doc/CPP_API.md). If you are a C/C++ beginner then I would highly recommend switching from macOS to Linux, because it is much simpler to compile and link against libprimesieve on Linux than on macOS and Windows. (I cannot help you with C/C++ compiling and linking issues on macOS and Windows)
