### ISSUE TITLE
[Suggestion] Allow boost multiprecision classes and GMP++ classes

### ISSUE THREAD

**Issue by BrainStone** [kimwalisch/primesieve#31]
it would be really cool if you could calculate arbitrarily large primes using `boost::multiprecision` and GMP (Or maybe even templates).

Like a library implementation similar to std::string would be useful. Meaning turning it into a template library but precompiling it for the default argument `uint64_t`

**Comment by kimwalisch** [comment]
I am asked about supporting primes > 2^64 about once a year and I have thought about whether or not to implement this quite extensively.

Here are the reasons why I will not implement this:

* Most libprimesieve use cases require generating small primes.
* The segmented sieve of Eratosthenes uses O(sqrt(n)) memory which becomes an issue above 2^64. E.g. primesieve would require > 1 terabyte of RAM for sieving near 10^25.
* The initialization time of the segmented sieve of Eratosthenes becomes a bottleneck past 2^64. The initialization could takes hours for large numbers even if sieving a tiny interval.
* libprimesieve should be extremely portable without any external dependencies.
* ```boost::multiprecision``` is not an option because it is so slow it is not even funny.

My main design goals for primesieve are: it should be self contained (no external dependencies), it should use only standard C++ and it should be extremely portable.

Sorry, I know supporting arbitrarily large primes would be cool but it won't happen.
