### ISSUE TITLE
Multithreaded and threadsafe primeiterator?

### ISSUE THREAD

**Issue by BrainStone** [kimwalisch/primesieve#32]
Would it be possible to implement a prime iterator that is threadsafe to use (out of the box) and that uses multithreading in it backend to speed up calculation?

**Comment by kimwalisch** [comment]
> Would it be possible to implement a prime iterator that is threadsafe to use (out of the box) and that uses multithreading in it backend to speed up calculation?

That is not a good idea because implementing a multi-threaded prime iterator would require synchronisation, it would probably not scale beyond 4 CPU cores.

Hence I suggest instead you use 1 ```primesieve::iterator``` per thread, this will scale well even with 100 CPU cores. I am using this approach myself in my primecount project e.g. here: https://github.com/kimwalisch/primecount/blob/master/src/P2.cpp#L70

This will require a little work by yourself to split up your algorithm into equally sized work chunks but I think it is worth the effort!

Let me know what you think...

**Comment by BrainStone** [comment]
Well that makes sense to an extend but in my use case it doesn't really work, as I need the product of all primes up to a certain one (checking all of them one after the other).

I was thinking about using a single thread generating the products and others testing them, but that would substatially increase memory usage and since the actual checking of a single product is essentially just taking it's square root and then doing some multiplication (meaning it's computed relatively quickly) the prime generation would most likely still be the bottle neck.

Regarless it was just a small project inspired by this video https://www.youtube.com/watch?v=aCq04N9it8U so it's not too big of an issue in my case.

But having a simple mutex mechanism in place would still be benificial (and is available in C++11. I'd recommend `std::lock_guard`)
