### ISSUE TITLE
Add current_prime to primeiterator

### ISSUE THREAD

**Issue by BrainStone** [kimwalisch/primesieve#33]
A method that just reads the current prime the primeiterator is at would be very useful in some cases.

**Comment by BrainStone** [comment]
And maybe add all operators and methods required so it becomes a valid BiDirectional Iterator.

**Comment by cgd8d** [comment]
Just an observation regarding the "bidirectional iterator" enhancement, since it could be easy to miss later on:  currently I believe that primesieve::iterator is not actually an iterator at all, in the sense that it is not CopyConstructible or CopyAssignable (https://en.cppreference.com/w/cpp/named_req/Iterator).  It contains a unique_ptr, which itself is not CopyConstructible or CopyAssignable, so primesieve::iterator does not have any default copy constructor or default copy assignment operator.  I ran into this when I tried to make copies of a primesieve::iterator; fortunately my use-case didn't really need the feature.

It wouldn't be a bad thing if primesieve::iterator had copy methods, although they might be expensive copies.

**Comment by kimwalisch** [comment]
@cgd8d Yes, you are right ```primesieve::iterator``` is not a valid C++ iterator but it was best name that I came up with in 2013 when I added the ```next_prime()``` and ```prev_prime()``` methods to primesieve. I still like the naming of ```primesieve::iterator```, personally I think it is a good choice.

When I first implemented ```primesieve::iterator``` I read up on how to implement a proper C++ iterator but it was so complicated and tricky that I decided against it (nobody on the internet could agree how to best implement a C++ iterator at that time). Another reason why I decided to not implement ```primesieve::iterator``` as a C++ iterator was that I preferred ```next_prime()``` and ```prev_prime()``` over ```prime++``` and ```prime--``` mainly because most other math libraries also use ```next_prime()``` and ```prev_prime()```.

> It wouldn't be a bad thing if primesieve::iterator had copy methods, although they might be expensive copies. ... I ran into this when I tried to make copies of a primesieve::iterator; fortunately my use-case didn't really need the feature.

I don't think this is a good idea, ```primesieve::iterator``` objects can allocate a large amount of memory to store the sieving primes e.g. up to 1.7 gigabytes near 2^64. Copying such an object would be very slow. What I could implement in a future version is deleted copy constructors and copy assignment operators so that nobody will run into your issue again.

Regarding the ```current_prime()``` method requested in this post I have to decline because it is not possible to implement it properly due to technical implementation details:

```primesieve::iterator``` is implemented using lazy evaluation i.e. when a new ```primesieve::iterator``` object is created it does not generate any primes, only when you call ```next_prime()``` or ```prev_prime()``` it will generate primes and return the next or previous prime. Hence when the ```primesieve::iterator``` object is initialized e.g. with a start number of 100 and you would call ```current_prime()``` (before calling  ```next_prime()``` or ```prev_prime()```) it is impossible to know if the user wants the first prime smaller or the first prime larger than 100. To fix this issue I would need to add error checking code to ```current_prime()``` which would make it slower than ```next_prime()``` or ```prev_prime()```, this is another reason why I don't like the idea of ```current_prime()```.

**Comment by cgd8d** [comment]
Thanks for your explanation, and that all makes sense.  Incidentally, I don't think you should need to delete the copy constructor and copy assignment operator because, now that you use unique_ptr, those functions should be default-deleted.  (Full disclosure:  My compiler, gcc 6.3, didn't seem to default-delete them.  That confused me and I spent a while unsuccessfully trying to understand why, so I just guessed/hoped that if I had a more recent compiler then they would have been default-deleted.  I don't think it has anything to do with your library.)

Also, just to be very clear, I agree the "iterator" name you use is completely appropriate and clear -- that didn't confuse me.  I just came across this open issue while searching for a better understanding of my own copy-related issue, and it seemed like a place to put my observation.  From my perspective it would be completely reasonable to close the issue as wontfix, and anyone who is curious why has a detailed explanation from you above.
