### ISSUE TITLE
primesieve 6.2 fails two tests on 32bit architectures

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#45]
According to Debian Package Auto-Building for the latest packaging for primesieve 6.2, [here](https://buildd.debian.org/status/package.php?p=primesieve), primesieve 6.2 fails two tests on the i386 architecture (and other 32bit arch): the involved tests are: floorPow2 and ilog2 .

**Comment by kimwalisch** [comment]
Hi Jerome,

* The ```ilog2.cpp``` test has been fixed by commit https://github.com/kimwalisch/primesieve/commit/a1d3a3b812360a52712990500542552f6d49cbf1
* The ```floorPower2.cpp``` test has been fixed by commit https://github.com/kimwalisch/primesieve/commit/6c74531408cab6d2f19f4bd0f71e3df69c328c85

The other bugs which are all related to:

```bash
libprimesieve.so.8.2.0: undefined reference to `__atomic_fetch_add_8'
```

are not primesieve bugs, these are caused by CPU architectures that currently don't fully support C++11 threading. The [build status ](https://buildd.debian.org/status/package.php?p=primesieve) shows that for each such failure the CPU architecture is out of date. I cannot fix these failures.

**Comment by jgmbenoit** [comment]
Thanks for the numerical fixes.
Otherwise, I am not sure what to understand by out of date CPU architecture: I guess it is more correct to say that the compiler doest not fully support C++-11 on some architectures. Of course we cannot fix the compiler (or the architectures). Given that, is there any work around that can be applied only on these exotic architecture ?

**Comment by kimwalisch** [comment]
> I guess it is more correct to say that the compiler doest not fully support C++-11 on some architectures. 

Yes, that is more accurate.

> Given that, is there any work around that can be applied only on these exotic architecture ?

Yes, I guess it is possible. This issue seems to be a known [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830942). Apparently the atomic features are not in ```libpthread.so``` on some Debian CPU architectures  but in ```libatomic.so```.

Hence a possible fix would be to add ```libatomic``` as a link dependency of ```libprimesieve``` and ```static_libprimesieve``` in CMakeLists.txt:

```diff
- target_link_libraries(libprimesieve Threads::Threads)
+ target_link_libraries(libprimesieve Threads::Threads atomic)

- target_link_libraries(static_libprimesieve Threads::Threads)
+ target_link_libraries(static_libprimesieve Threads::Threads atomic)
``` 

However I cannot test if this really fixes the issue. I found one [other open source project](https://github.com/bmwcarit/meta-ros/commit/859f5da5cb2320e67f63f826ec4b07ffd4af83a6#diff-99d04d85dace17a70c34a8df2543f701R12) that fixed the same issue this way.

**Comment by jgmbenoit** [comment]
Ok. Can you make conditional/optional in CMakeLists.txt ?
And then release a micro version in such a way I can easily repack and test ?

**Comment by kimwalisch** [comment]
>Ok. Can you make conditional/optional in CMakeLists.txt ?
>And then release a micro version in such a way I can easily repack and test ?

Yes, but it will take a few hours because I need to test this myself a little (I am worried libatomic might not exist on some systems (e.g. Windows) and ```CMakeLists.txt``` must handle this correctly).

**Comment by jgmbenoit** [comment]
I understand. Take you time. It would be nice if you can test it on Debian derived box.
For Debian, I will trigger it only where it is required.

**Comment by kimwalisch** [comment]
I have now merged the fix for the libatomic linker error. I have tested the fix on Debian, Ubuntu, Red Hat, macOS and Windows. ```CMakeLists.txt``` now correctly finds libatomic and adds it as a link dependency to ```libprimesieve```(but only if this is really needed).

I am not 100% sure if it works though as I don't have access to any of the Debian architectures where the primesieve-6.2 build failed.

I have released [primesieve-6.3-rc1](https://github.com/kimwalisch/primesieve/releases) for testing.

**Comment by jgmbenoit** [comment]
Thanks for your prompt fix. I will have a look on next Friday.

**Comment by jgmbenoit** [comment]
I have just tested primesieve-6.3-rc1 on an armel box: the built and the tests work.
When do you plan to release the version 6.3 ?

**Comment by kimwalisch** [comment]
If v6.3-rc1 works for you I will release primesieve-6.3 tomorrow, v6.3 will
contain no code changes compared to v6.3-rc1.

Regards,
Kim

**Comment by kimwalisch** [comment]
Hi Jérôme,

I have released primesieve-6.3 on GitHub:
https://github.com/kimwalisch/primesieve/releases

Kim

**Comment by jgmbenoit** [comment]
So I have begun to package. It appears that the check in CMakeLists.txt see whether or not the atomic material comes from the compiler itself or from the adhoc libatomic library. I will dig the issue next week-end. Sorry for the delay.

**Comment by kimwalisch** [comment]
> It appears that the check in CMakeLists.txt see whether or not the atomic
material comes from the compiler itself or from the adhoc libatomic library.

Yes, while searching for the error using Google I found that the LLVM
compiler had the same issue: https://reviews.llvm.org/D10453 (also bug
explained here:
https://answers.launchpad.net/gcc-arm-embedded/+question/616213). And as
LLVM also uses cmake as its build system I cloud see how they fixed the
issue and implement something similar. As far as I understand this issue
exists on CPU architectures that do not have the required atomic
instructions to support C++11 atomics, in this case using C++11 atomics
requires linking against libatomic. Hence in CMakeLists.txt I first check
whether C++11 atomic compiles without libatomic, if it does not compile I
add libtoamic to the linker flags.

Kim

**Comment by jgmbenoit** [comment]
Yes but as libatomic is installed and it is meant to be transparent at build time, the test is lure.
Having said that, I have noticed that some tests are lasting extremely long on armel. So, you might consider to avoid atomic feature when it is not engraved in the CPU.

**Comment by kimwalisch** [comment]
> Having said that, I have noticed that some tests are lasting extremely long on armel.

* How how long did it take to complete primesieve's test suite on armel?
* What are the 2 slowest tests on armel?

My goal with primesieve's test suite has been that it should complete in about 30 seconds on a recent x86 CPU. Unfortunately this also means that if the test suite is run on a very old or low power embedded CPU running the test suite might take much longer. E.g. For the hppa CPU (which I guess is at least 15 years old) primesieve-6.2 took [2430 seconds](https://buildd.debian.org/status/fetch.php?pkg=primesieve&arch=s390x&ver=6.2%2Bds-1&stamp=1510442775&raw=0) to complete its test suite.

Looking at the build time and test time of the gmp C multiprecision library for the hppa CPU I see that it even took [1h 17m](https://buildd.debian.org/status/logs.php?pkg=gmp&arch=hppa&suite=sid). So other libraries are having the same issue.

This is not an easy fix because I cannot simply reduce the tests by a factor of 100 just to reduce the test suite runtime on some ancient CPUs...

>So, you might consider to avoid atomic feature when it is not engraved in the CPU.

I am quite sure that the long test run times are not related to the use of atomic instructions. Atomics are obviously only used when using multi-threading but e.g. for the hppa architecture many long running tests: ```generate_primes2```, ```next_prime2```, ```prev_prime1```, ```generate_n_primes1``` are single-threaded tests. Also atomics are used extremely sparsely in primesieve so that even if the CPU does not support hardware atomics this will not affect primesieve's run-time.

**Comment by jgmbenoit** [comment]
I will record the time next time. BTW, it can be an issue for automates at building time; we will see.
Otherwise, do you have any idea how to harden the test ?

**Comment by kimwalisch** [comment]
> do you have any idea how to harden the test?

Sorry, but I don't understand what you mean?

**Comment by jgmbenoit** [comment]
The current test does not work. If libatomic is installed, the test set have_atomic to true.

**Comment by kimwalisch** [comment]
My understanding is that have_atomic is set to true only if the compiler is able to compile std::atomic without linking against libatomic. In this case libatomic is not needed.

If however have_atomic is false than we need to link against libatomic. 

I have tested this on i386 and x64 and there it worked fine.

**Comment by jgmbenoit** [comment]
it does not work on armel .

**Comment by kimwalisch** [comment]
Ok, can you print the cmake (and make) output here so that I can see what went wrong?

**Comment by kimwalisch** [comment]
> it does not work on armel.

I have been able to reproduce the bug on my old 32-bit PowerPC Mac. The issue is that these old CPU architectures do have 32-bit atomic instructions but not 64-bit atomic instructions. Hence my ```have_atomic``` test which used ```std::atomic<int>``` passed fine but then primesieve failed to compile because it uses ```std::atomic<int64_t>```.

Hence I have now modified the test in CMakeLists.txt to use ```std::atomic<int64_t>``` and now the test correctly fails on my 32-bit PowerPC Mac.

```cmake
check_cxx_source_compiles("
    #include <atomic>
    #include <stdint.h>
    int main() {
        std::atomic<int64_t> x;
        x = 1;
        x--;
        return (int) x;
    }"
    have_atomic)
```

Can you please retest using the latest code from the master branch?

**Comment by jgmbenoit** [comment]
Sorry for my late reply. It works on armel. I am on way to test on other architectures.

**Comment by kimwalisch** [comment]
> Sorry for my late reply. It works on armel. I am on way to test on other architectures.

Thanks, once you have tested it successfully on other architectures I will bump the version number again and release 6.4. I misunderstood you last week, I thought it was working without any issues that's why I released 6.3 last week, otherwise I would have fixed this issue first before releasing version 6.3.

**Comment by jgmbenoit** [comment]
The suggested test works at least on the mipsel, mips, and armel architectures (which architect officially supported by Debian).
The time for the test are:
armel: 1175.13 s
mips: 707.6 s
mipsel: 417.96 s

Concerning realising, you did misunderstand my claim, but I rather overestimated my own test; I am sorry for that.
Given that, I do not think it is necessary to make a new release: let apply a patch and see if it works well on all architectures (officially or not supported by Debian).

**Comment by kimwalisch** [comment]
> Given that, I do not think it is necessary to make a new release: let apply a patch and see if it works well on all architectures (officially or not supported by Debian).

OK, I like this solution better.

**Comment by jgmbenoit** [comment]
It rocks ! In about 5 days, it should reach testing. Thank you very much for your patience.
