### ISSUE TITLE
Simple is_prime fucntionality in API

### ISSUE THREAD

**Issue by BrainStone** [kimwalisch/primesieve#55]
Hi it's me again 😅 

So this time my suggestion is a simple class that allows to check if a number is a prime number, backed by a primeiterator. I know this is not very hard to implement, but I think it would be a useful thing to have. Maybe even just expose some already existing external code in the API would be enough.

I could also imagine quickly throwing some code together in a PR that would be exactly such a class.

**Comment by kimwalisch** [comment]
Hi BrainStone,

> So this time my suggestion is a simple class that allows to check if a number is a prime number, backed by a primeiterator.

You could use something like:

```C++
bool is_prime(uint64_t n)
{
    return primesieve::count_primes(n, n) == 1;
}
```

This will have the same performance as an ```is_prime(n)``` function based on a ```primesieve::iterator```. The runtime complexity of such an ```is_prime(n)``` implementation is O(r * log log r) with r=sqrt(n).

I agree that adding an ```is_prime(n)``` function to primesieve is a good idea but I would not like to add an ```is_prime(n)``` implementation based on ```primesieve::iterator``` or ```primesieve::count_primes()``` because there are much faster algorithms e.g. ```is_prime(n)``` using ```primesieve::iterator``` would take more than 2 seconds to check a number near 2^64 while there are other algorithms that can check primality of a number near 2^64 in a few microseconds (Dana Jacobson's Perl Math::Prime::Util library has a very fast ```is_prime(n)``` function: https://metacpan.org/pod/Math::Prime::Util#PRIMALITY-TESTING).

Implementing a fast ```is_prime(n)``` that is competitive with other libraries such as [Math::Prime::Util](https://metacpan.org/pod/Math::Prime::Util) is a lot of work (I guess between 6 months and a year of development) and not on top of my priority list.

**Comment by BrainStone** [comment]
That's fair. A simple implemenation on either of the two methods provided sounds like a neat temporary solution.
I personally really like the iterator solution, as it would make repetetive use fast. That's also why I suggested making a class for it. So you can free the memory when you're done checking the primality of numbers.

Does `primesieve::count_primes` do caching or does it calculate the primes each time?

**Comment by kimwalisch** [comment]
> Does primesieve::count_primes do caching or does it calculate the primes each time?

```primesieve::count_primes()``` does not do any caching,  it re-calculates the primes each time. But the ```primesieve::iterator``` solution does not do any caching either unless you implement the caching yourself.

The run-time complexity of ```is_prime(n)``` can be reduced to O(sqrt(n) / log(n)) if all primes are cached in an array. This sounds great at first, however the most expensive operation of ```is_prime(n)``` is the integer modulo that needs to be calculated for each prime <= sqrt(n). And the number of such integer modulo operations is the same with or without caching.

Personally I guess caching could speed up ```is_prime(n)``` by about 30% but I don't think caching is worth it because is uses a lot of memory e.g. caching all primes < 2^32 in an array requires at least 775 megabytes of RAM.

I agree that using ```primesieve::iterator``` is cleaner than using ```primesieve::count_primes()```.

```C++
bool is_prime(uint64_t n)
{
    uint64_t prime; 
    uint64_t sqrt = (uint64_t) std::sqrt(x);
    primesieve::iterator it;

    while ((prime = it.next_prime()) <= sqrt)
        if (n % prime == 0)
            return false;

    return true;
}
```

However there is a **pitfall**:

```std::sqrt``` is accurate only up to 2^53 due to its use of the ```double``` type. This pitfall does not exist using ```primesieve::count_primes()``` because primesieve uses its own ```isqrt()``` function internally that works correctly for all integers. So if you want to go with the ```primesieve::iterator``` solution you will probably have to write your own ```isqrt()``` function...

**Comment by BrainStone** [comment]
Thanks for the information!

I want check the primalitiy of GMP numbers, so I can use their built in `isqrt`. But thanks for your insight!
And even more for creating this amazing project!

And by caching using an iterator I mean using one iterator object per thread and always just resetting it, as it should do some caching from what I read in the code.

Anyways, I'll use that code for now and will try better algorithms like AKS (example implementation that uses GMP can be found here: https://github.com/danaj/Math-Prime-Util-GMP/blob/master/aks.c)

**Comment by BrainStone** [comment]
I have another quick question:

Is there a way to reach out to you for causual chatting about primes, math and optimizing stuff? I'd surely understand if you are not up for something like that, but if you are I'd love to know where the best place would be. Or maybe there's even a community where people chat about stuff like that.
