### ISSUE TITLE
Using project as a dynamic library

### ISSUE THREAD

**Issue by Najsr** [kimwalisch/primesieve#58]
Hello, I've wanted to ask if it is possible to compile this project as a dynamic library in windows. I have successfully compiled from source the exe file but i am not sure how to get dll. (I'd like to use it to make a wrapper for C#).

Thanks,
David.

**Comment by kimwalisch** [comment]
Hi David,

Unfortunately building primesieve as a shared library is not yet supported on Windows. Quite a few users have already requested this feature in the past but every time I googled on how to implement this I got extremely annoyed about how difficult and cumbersome it is to support shared libraries on Windows.

So now I googled again and found that CMake seems to have improved Windows shared library support since version 3.4. I will to build a shared library on Windows using CMake and let you know if I succeeded. If it works well I will a this feature to the next primesieve release.

**Comment by Najsr** [comment]
Thanks for the quick answer, I am really looking forward to see the new library if everything goes as planned.

**Comment by Najsr** [comment]
Hello, I have successfully compiled it as the library. But there is a small "problem" in method names.
part of dumpbin:
```
        499  1F2 000026F0 primesieve_count_primes
        500  1F3 00002720 primesieve_count_quadruplets
        501  1F4 00002750 primesieve_count_quintuplets
        502  1F5 00002780 primesieve_count_sextuplets
        503  1F6 000027B0 primesieve_count_triplets
        504  1F7 000027E0 primesieve_count_twins
        505  1F8 00002810 primesieve_free
        506  1F9 000070C0 primesieve_free_iterator
        507  1FA 00002820 primesieve_generate_n_primes
        508  1FB 00007160 primesieve_generate_next_primes
        509  1FC 00007310 primesieve_generate_prev_primes
        510  1FD 000028E0 primesieve_generate_primes
        511  1FE 000029B0 primesieve_get_max_stop
        512  1FF 000029C0 primesieve_get_num_threads
        513  200 000029D0 primesieve_get_sieve_size
        514  201 00007450 primesieve_init
        515  202 000029E0 primesieve_nth_prime
        516  203 00002A10 primesieve_print_primes
        517  204 00002A30 primesieve_print_quadruplets
        518  205 00002A50 primesieve_print_quintuplets
        519  206 00002A70 primesieve_print_sextuplets
        520  207 00002A90 primesieve_print_triplets
        521  208 00002AB0 primesieve_print_twins
        522  209 00002AD0 primesieve_set_num_threads
        523  20A 00002AE0 primesieve_set_sieve_size
        524  20B 000074C0 primesieve_skipto
        525  20C 00002AF0 primesieve_version
```
The problem is I have to import dll with entry point "primesieve_count_primes". It is not a real deal but would be nice if it was just "count_primes".
Thanks.

**Comment by kimwalisch** [comment]
Hi David,

> The problem is I have to import dll with entry point "primesieve_count_primes". It is not a real deal but would be nice if it was just "count_primes".

primesieve has both a C API ([primesieve.h](https://primesieve.org/api/primesieve_8h.html)) and a C++ API ([primesieve.hpp](https://primesieve.org/api/primesieve_8hpp.html)). All names that start with ```primesieve_*``` are part of primesieve's C API. Many C libraries actually use the same naming convention for functions names because C does not support namespaces (examples: [zstd](https://facebook.github.io/zstd/zstd_manual.html#Chapter4), [libgit2](https://libgit2.org/libgit2/#HEAD), [cairo](https://www.cairographics.org/manual/cairo-Regions.html)). Personally I like primesieve's C API, it is consistent, easy to use and extremely fast. If you don't like using e.g. primesieve_count_primes in your code then I suggest you create yourself shorter wrapper functions around the primesieve C API.

primesieve's C++ is a little nicer and you can get exactly what you want in C++ by importing the primesieve namespace:

```C++
// C++
uint64_t count = primesieve::count_primes(start, stop);

using namespace primesieve;
count = count_primes(start, stop);
```

But most programming languages have better interoperability with C than C++ and that's why many people use primesieve's C API. (I don't know whether C# has good interoperability with C++)

**Comment by Najsr** [comment]
Well I am using DllImport functionality in C# which uses exposed C functions. But you can specify entry point in the parameters so it is just fine.
So is there any ETA for it to getting pushed into master and added to releases?

**Comment by kimwalisch** [comment]
> So is there any ETA for it to getting pushed into master and added to releases?

Yes, the next primesieve version will build primesieve.dll by default on Windows. It will take some time though, not because the code change are hard (in fact they are trivial) but I would like to ensure that it works without any issues using many different C++ Windows compilers (e.g. MSVC, MinGW, clang-cl, Intel C++ compiler).

> ... and added to releases?

Is my understanding correct here that you would like me to offer primesieve.dll as a download for each release so that you don't need to compile it yourself? I guess this only makes sense if the primesieve.dll I compiled works with multiple MSVC compiler versions (I have to do some research for that).

**Comment by kimwalisch** [comment]
DLL support has been merged into master: https://github.com/kimwalisch/primesieve/pull/60. libprimesieve is now built by default as a static and shared library (DLL) on Windows.

It has been tested successfully using the following compilers:

* MSVC
* clang-cl
* Intel C++ Compiler
* MinGW
* Cygwin
