### ISSUE TITLE
Feature request:  iterator move-constructor and move-assignment

### ISSUE THREAD

**Issue by cgd8d** [kimwalisch/primesieve#65]
The following silly code currently fails to compile:

    #include "primesieve.hpp"
    
    int main()
    {
      std::vector<primesieve::iterator> vec;
      vec.emplace_back(0, 1000); // Requires move-constructor
      primesieve::iterator it2, it3;
      it2 = std::move(it3); // Requires move-assignment
    }

This can be fixed by declaring a default move-constructor and move-assignment operator.  Code could be as follows.

In iterator.hpp:

    iterator(iterator&&);
    iterator& operator=(iterator&&);

In iterator.cpp:

    iterator::iterator(iterator&&) = default;
    iterator& iterator::operator=(iterator&&) = default;

Although the example is purely silly, I think it would do no harm to provide these functions, and would support some convenient manipulations of iterators.  For myself, storing a small collection of iterators in a std::vector would be convenient.

**Comment by kimwalisch** [comment]
Questions:

* Can we define the default move-constructor and move-assignment operator in the header?
* Is there any advantage of defining the move-constructor and move-assignment operators in the cpp file?

One benefit I see is that if we add move-constructor and move-assignment operators to ```primesieve::iterator``` then the default copy constructor and copy assignment operator will be disabled automatically. And since you have run into this issue I expect other users to also run into this issue. (As you pointed out though theoretically ```primesieve::iterator``` should not be copyable because it has a ```std::unique_ptr``` which is not copyable).

**Comment by kimwalisch** [comment]
OK, I have now tried to define the move-constructor and move-assignment operators in the header and it does not work because the ```PrimeGenerator``` type is forward declared in ```iterator.hpp```.

```
In file included from /home/kim/Desktop/primesieve-7.2/include/primesieve/iterator.hpp:18:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/memory:80:
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/unique_ptr.h:76:16: error: invalid application of 'sizeof' to an incomplete type 'primesieve::PrimeGenerator'
        static_assert(sizeof(_Tp)>0,
                      ^~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/unique_ptr.h:268:4: note: in instantiation of member function 'std::default_delete<primesieve::PrimeGenerator>::operator()'
      requested here
          get_deleter()(__ptr);
          ^
/home/kim/Desktop/primesieve-7.2/include/primesieve/iterator.hpp:75:1: note: in instantiation of member function 'std::unique_ptr<primesieve::PrimeGenerator,
      std::default_delete<primesieve::PrimeGenerator> >::~unique_ptr' requested here
iterator(iterator&&) = default;
^
/home/kim/Desktop/primesieve-7.2/include/primesieve/iterator.hpp:22:7: note: forward declaration of 'primesieve::PrimeGenerator'
class PrimeGenerator;
      ^
1 warning and 1 error generated.
```

But using your code (define in ```iterator.cpp```) it works as expected.

**Comment by kimwalisch** [comment]
Apparently it is good practice to declare the move-constructor and move-assignment operators as ```noexcept``` . Most C++ objects in the STL also do this e.g. [unique_ptr](https://en.cppreference.com/w/cpp/memory/unique_ptr/operator%3D).

```C++
// iterator.hpp:
iterator(iterator&&) noexcept;
iterator& operator=(iterator&&) noexcept;
```

```C++
// iterator.cpp:
iterator::iterator(iterator&&) noexcept = default;
iterator& iterator::operator=(iterator&&) noexcept = default;
```

See this [blog post](https://akrzemi1.wordpress.com/2015/09/11/declaring-the-move-constructor/) for in depth explanation.

**Comment by cgd8d** [comment]
Thanks for taking such an in-depth look at this -- I hadn't considered
noexcept.  One observation:  std::vector only declares its move constructor
and move assignment as noexcept only starting in C++17.  It looks like
primesieve currently uses "std=c++14".

I'm getting conflicting information about what this means.  The blog post
you cited says that a compile-time error (for implementations which may
throw from the vector functions) is the result.  But
https://en.cppreference.com/w/cpp/language/noexcept_spec says that the
result is valid regardless, and if an exception hits your noexcept
specifier at runtime, stack unwinding fails and std::terminate is called.

For my compiler (gcc 6.3) I have no compile-time issues (and I'm not
running code that needs to handle exceptions cleanly, so terminating is
fine for me), and starting with C++17 noexcept would unquestionably be the
right thing.  So I have no opinion on the right choice here.

**Comment by kimwalisch** [comment]
I have now added move semantics to ```primesieve::iterator``` using ```noexcept``` (see [pull/66](https://github.com/kimwalisch/primesieve/pull/66/files)). I have also written a test [move_primesieve_iterator.cpp](https://github.com/kimwalisch/primesieve/blob/master/test/move_primesieve_iterator.cpp) which adds ```primesieve::iterator``` objects to a ```std::vector```, the test compiles and runs successfully using GCC, Clang and MSVC.

> One observation:  std::vector only declares its move constructor and move assignment as noexcept only starting in C++17.

My ```std::vector``` test compiles and runs fine even with ```-std=c++11``` and since ```noexcept``` move semantics seem to be the future I want my code to be future proof and hence I am also using ```noexcept```.

> It looks like primesieve currently uses "std=c++14".

primesieve's CMake build system is configured to not use a specific C++ version but to use the compiler's default C++ version setting. Once compilers will switch to C++17 by default primesieve will also use C++17.

Note that I even though I have merged the move semantics code into the master branch I won't immediately do a new primesieve-7.3 release. I will wait a few more months until more users' feature requests have been implemented.

**Comment by cgd8d** [comment]
Looks great, thanks!

**Comment by kimwalisch** [comment]
> It wouldn't be a bad thing if primesieve::iterator had copy methods, although they might be expensive copies.

@cgd8d I just realized that it is actually quite easy to add copy methods to ```primesieve::iterator```. The idea is to **not** make a deep copy of all the data structures and sieving primes but instead just set the start number of the new ```primesieve::iterator``` object to the current prime of the old ```primesieve::iterator```. The new ```primesieve::iterator``` object would then only generate new primes once ```next_prime()``` or ```prev_prime()``` is called for the first time (using lazy initialization).

Can you please explain how you tried to copy ```primesieve::iterator``` objects? Do you remember the code e.g. did you try to ```push_back()``` a  ```primesieve::iterator``` onto a ```std::vector```? By understanding your use case I can evaluate if I should prevent people from doing copies because of the performance overhead or if I should allow it...

**Comment by cgd8d** [comment]
It sounds like what you're suggesting would be basically equivalent to constructing a new primesieve::iterator and calling skip_to?  So, I assume that you're looking for a syntax-based reason to support copy, rather than an algorithmic need.

Well, yes, I was trying to push_back a primesieve::iterator onto a std::vector.  Basically, I am looking at colossally abundant numbers, and to do that I keep multiple primesieve::iterators in a vector which each progress forward at different times.  But now that the move operators are supported, I can basically do something just as good; and if I needed to construct a new primesieve::iterator at a certain start value and move it into the vector to imitate a copy, that would be fine.

So, I don't have an application which requires a true copy operation.  The only reason I can think of would be if you did plan to make primesieve::iterator a Bidirectional Iterator so it could be used by generic C++ algorithms (not sure which generic algorithms exactly, since it's not in my use-case).  You mentioned in https://github.com/kimwalisch/primesieve/issues/33#issuecomment-441393997 that in addition to the copy issue, there is no well-defined current_prime value, so that may still be a non-starter.

**Comment by kimwalisch** [comment]
> But now that the move operators are supported, I can basically do something just as good; and if I needed to construct a new primesieve::iterator at a certain start value and move it into the vector to imitate a copy, that would be fine.

Thanks for your feedback. So for the time being I will not add copy methods because the implementation I had in mind is kind of a hack and because copy methods don't seem that useful now that move semantics are supported.

> You mentioned in #33 (comment) that in addition to the copy issue, there is no well-defined current_prime value, so that may still be a non-starter.

Yes, I have declined adding ```current_prime()``` to ```primesieve::iterator``` because it requires error handling when no current prime exists yet. In C++ I would have throw an exception which is not ideal. But in C it gets really ugly because I would have to e.g. set ```errno``` and I cannot reasonably expect users to check ```errno``` after each ```current_prime()``` call.
