### ISSUE TITLE
Big numbers support

### ISSUE THREAD

**Issue by vk496** [kimwalisch/primesieve#68]
Hello,

Is there support for big numbers?

Something like this:

```cpp
#include <cstdlib>
#include <iostream>
#include <primesieve.hpp>

using namespace std;

int main(int argc, char** argv) {
    
    primesieve::iterator it;
    
    it.skipto(99999999999999999999999999999999999999999);
    
    uint64_t prime = it.next_prime();
    
    std::cout << prime << std::endl;
    
    return 0;
}
```

Maybe I am missing something....

Salu2

**Comment by kimwalisch** [comment]
Hi,

I am sorry but primesieve can only generate primes up to 2^64. And primesieve will most likely never support generating primes > 2^64 because the sieve of Eratosthenes algorithm is not suited for generating large primes.

If you need a library for generating large primes I can recommend [Math-Prime-Util](https://metacpan.org/pod/Math::Prime::Util).
