### ISSUE TITLE
Bindings for other languages

### ISSUE THREAD

**Issue by hickford** [kimwalisch/primesieve#8]
Do you know of bindings for other languages—Python, Ruby and so on? If you do, please could you link them from the readme or faq.

**Comment by hickford** [comment]
I'd love to use this library from Python. I found https://github.com/jaredks/pyprimesieve but it doesn't work in recent Python versions (3.x)

**Comment by kimwalisch** [comment]
> Do you know of bindings for other languages

I wrote the C bindings myself. I agree that it would be useful to have bindings for a few other popular languages especially Python and C#. So far I have not written such bindings because I am obsessed about high quality code and I don't have much experience with these languages.

I also came across https://github.com/jaredks/pyprimesieve but I have never used it. If you know Python 3 then I guess it should not be too difficult for you to port the library to Python 3. I like your suggestion to add a section about other language bindings to primesieve's README.md. I will probably work on this (maybe even write other bindings myself) in the next weeks.

**Comment by kimwalisch** [comment]
I just recall there is another option for using primesieve from Python:

https://github.com/sympy/symengine

I have never used it but I think you first need to build the library yourself using:

```
CC=clang CXX=clang++ cmake -DWITH_PRIMESIEVE:BOOL=ON .
```

**Comment by hickford** [comment]
Hi Kim. Cool. I've installed the command line primesieve app, it is **orders of magnitude** faster than the Python code I'm using at the moment.

Right! I'm having some kind of fun trying to write a wrapper in Cython http://cython.org/ . Stumped at the moment https://stackoverflow.com/questions/31215419/whats-wrong-with-my-cython

There's also SWIG but I don't know anything about it http://www.swig.org/

**Comment by kimwalisch** [comment]
> I'm having some kind of fun trying to write a wrapper in Cython http://cython.org/ .

Please keep me updated on your wrapper. If it works reasonably well I would like to add it to the new "Bindings for other languages" section that I will create in my README.md. I am also interested in contributing to your wrapper so it would be great if you published your wrapper on GitHub.

**Comment by hickford** [comment]
Great! Here's my progress https://github.com/hickford/primesieve-python I hope to publish something to PyPI this weekend.

You're most welcome to contribute

**Comment by jaredks** [comment]
Hello there.

Just want to let people know that I've updated https://github.com/jaredks/pyprimesieve to work with any recent Python version.

**Comment by hickford** [comment]
Hi Jared, cool. My project is probably superfluous, but I'm happy to have learnt about Python extensions.

**Comment by Ismael-VC** [comment]
I also want to use this from whithin [Julia](https://github.com/JuliaLang/julia). Currently I'm testing with the `Cxx` package:

* https://github.com/Keno/Cxx.jl
