### ISSUE TITLE
Misplaced "static inline" in c header file iterator.h

### ISSUE THREAD

**Issue by AaronChen0** [kimwalisch/primesieve#85]
Hi, @kimwalisch.  
I am trying making a common lisp binding for libprimesieve.
But I find the "primesieve_next_prime" and "primesieve_prev_prime" function in c header file  [iterator.h](https://github.com/kimwalisch/primesieve/blob/master/include/primesieve/iterator.h#L67) are declared "static inline", while the other two for internal use are not declared "static inline".
Is this a mistake?

**Comment by kimwalisch** [comment]
> But I find the "primesieve_next_prime" and "primesieve_prev_prime" function in c header file iterator.h are declared "static inline", while the other two for internal use are not declared "static inline".
Is this a mistake?

The ```primesieve_next_prime``` and ```primesieve_prev_prime``` functions are declared inline as they contain code. The other functions are just function declarations (as opposed to function definitions) that do not contain any code, hence they are not declared ```inline```. So I think everything is correct.

Generally in C when you put inline functions in a header you also add ```static``` because otherwise that code will always be included in the compiled binary even if the code is not used.

However the 2 inline functions will make writing a binding a little more cumbersome. I think you need to write 2 Lisp wrapper functions for the 2 inline functions and translate the inline code to Lisp. I suggest that you look how other people how written bindings for the 2 inline functions in other programming languages.

**Comment by AaronChen0** [comment]
You are right. I will write 2 lisp functions to wrap those 2 internal-used C functions. Thank you.
