### ISSUE TITLE
Feature request: serialise / restore from checkpoint

### ISSUE THREAD

**Issue by balping** [kimwalisch/primesieve#97]
When iterating over primes it would be nice if I could save the entire inner state of the prime generator (ie. sieve), so that the computation could be continued easily from a given checkpoint. I'm aware of the `it.skipto()` function, but restoring the entire sieve might be faster for large primes.

Example API:

Saving:
```c++
primesieve::iterator it;
it.next_prime(); // many times
buffer << it.serialise();
```

Loading
```c++
primesieve::iterator it;
it.restore() << buffer;
it.next_prime(); 
```

**Comment by kimwalisch** [comment]
This feature request is the same as asking to add a copy constructor to primesieve. Other users have already requested this feature before.

The problem with this feature request is that it is difficult to implement. It requires making a copy of every single data structure used by the ```primesieve::iterator``` object (which use lots of data structure and up to 1.7 gigabytes of memory). On top of that primesieve stores pointers in the bucket data structure. So simply making a copy of the bucket data structures does not work, you also need to update the pointers which is quite difficult to implement.

So as a summary: adding this feature would be a significant amount of work and it would add a lot of complexity to primesieve. Personally I think this feature would only be used rarely. For these reasons I will not implement this feature request at this point in time. But I will leave this issue open so that other users can read it.

**Comment by balping** [comment]
Ok, thanks for the explanation.
